random_seed: 42
use_gpu: true

# --- Data Configuration ---
use_dummy_data_for_full_run: false # SET TO FALSE TO USE REAL DATA
data_dir: "data/"
data_paths:
  train: "trainData.csv"
  val: "valData.csv"
  target_column: "outcomeType"
# GNN related data column - will be generated if set to 'graph_instance_id'
patient_id_column: 'graph_instance_id' # Instructs train.py to generate per-row IDs

# Dummy data settings (only used if use_dummy_data_for_full_run is true)
dummy_data_total_samples: 1000
dummy_data_features: 50
dummy_data_classes: 2
dummy_data_weights: [0.85, 0.15]

# --- Preprocessing Configuration ---
preprocessing:
  numerical_cols: [
    "requestDate",
    "admissionDate",
    "patientAge",
    "glasgowScale",
    "hematocrit",
    "hemoglobin",
    "leucocitos",
    "lymphocytes",
    "urea",
    "creatinine",
    "platelets",
    "diuresis",
    "lengthofStay"
  ]
  categorical_cols: [
    "requestType",
    "requestBedType",
    "admissionBedType",
    "admissionHealthUnit",
    "patientGender",
    "patientFfederalUnit",
    "icdCode",
    "blodPressure"
  ]
  imputation_strategy: 'median'
  scale_numerics: true
  onehot_handle_unknown: 'ignore'

# --- Balancing Configuration ---
balancing:
  use_rsmote_gan_in_cv: true # Re-enabled for more comprehensive run
  rsmote_gan_params:
    k: 5
    minority_upsample_factor: 3.0

# --- Ensemble Configuration ---
ensemble:
  n_outer_folds: 5 # Increased for comprehensive evaluation
  n_inner_folds_for_oof: 5 # Increased for comprehensive evaluation

  train_lgbm: true
  train_teco: true
  train_gnn: false # Keeping GNN Disabled for now to manage complexity
  train_meta_learner: true

  lgbm_params:
    num_leaves: 127
    class_weight: 'balanced'
    learning_rate: 0.05
    reg_alpha: 0.1
    reg_lambda: 0.1
    min_child_samples: 20
    colsample_bytree: 0.7
    subsample: 0.7
    num_boost_round: 200 # Increased for comprehensive evaluation
    early_stopping_rounds: 30 # Increased for comprehensive evaluation
    save_path: 'models_output/lgbm_final_ncv_trained.joblib'

  teco_params:
    input_feature_dim: null
    d_model: 512
    num_encoder_layers: 4
    nhead: 8
    dim_feedforward: 2048
    dropout: 0.1
    num_classes: null
    max_seq_len: 150
    epochs_teco_inner: 10 # Increased for comprehensive evaluation
    batch_size_teco: 32
    lr_teco: 0.00005
    save_path: 'models_output/teco_final_ncv_trained.pth'

  # Parameters for HeteroTemporalGNN (as used in train.py)
  gnn_params:
    # Data related columns for GNN
    data_columns:
      vital_columns: [
        "patientAge", "glasgowScale", "hematocrit", "hemoglobin",
        "leucocitos", "lymphocytes", "urea", "creatinine",
        "platelets", "diuresis"
      ]
      diagnosis_column: "icdCode"
      medication_column: null
      procedure_column: null
      event_timestamp_column: "admissionDate"
      label_timestamp_column: "admissionDate"
      admission_timestamp_column: "admissionDate"

    # Model Hyperparameters for HeteroTemporalGNN
    concept_embedding_dim: 64
    gnn_hidden_dim: 128
    gnn_output_dim: 128
    num_gnn_layers: 3
    num_gat_heads: 4
    dropout_rate: 0.2
    timeslice_feature_dim: null

    # Training Hyperparameters for GNN (per inner fold)
    epochs_inner: 5 # <<<< MODIFIED FOR QUICKER TEST
    lr: 0.0005
    batch_size: 32

    # Graph construction and processing
    graph_construction_params:
      time_embedding_dim: 16
    force_reprocess_graphs: true
    save_path: 'models_output/hetero_gnn_final_ncv_trained.pth'


  meta_learner_xgb_params:
    depth: 3
    num_boost_round: 100      # Increased for comprehensive evaluation
    early_stopping_rounds: 15 # Increased for comprehensive evaluation
    scale_pos_weight: 2.5     # Fixed value for cost-sensitive learning
    save_path: 'models_output/meta_learner_xgb_ncv_trained.joblib'

  soft_vote_weights:
    lgbm: 0.4
    teco: 0.4 # <<<< MODIFIED: Adjusted for GNN
    gnn:  0.2 # <<<< MODIFIED: Added GNN weight

# --- W&B Logging ---
wandb:
  project: 'ifbme-project-accuracy-push' # New project name for this iteration
  entity: null
  run_name: 'ncv_run_gnn_lgbm_tuned_meta_fix_attempt'
  run_notes: 'NCV run with GNN enabled, LightGBM params tuned, meta-learner rounds increased, TECO params adjusted.'
  tags: ['accuracy_push', 'gnn_enabled', 'lgbm_tuned', 'ncv']

# --- Output Directory ---
output_dir: "outputs"