# Simplified configuration for the IUPESM 2025 challenge

random_seed: 42
data_dir: 'data/'
output_dir: 'outputs/'
los_column: 'LengthOfStay'

# Preprocessing settings
preprocessing:
  numerical_cols:
    - 'admission_age'
    - 'heart_rate_min'
    - 'heart_rate_max'
    - 'heart_rate_mean'
    - 'sbp_min'
    - 'sbp_max'
    - 'sbp_mean'
    - 'dbp_min'
    - 'dbp_max'
    - 'dbp_mean'
    - 'mbp_min'
    - 'mbp_max'
    - 'mbp_mean'
    - 'resp_rate_min'
    - 'resp_rate_max'
    - 'resp_rate_mean'
    - 'temperature_min'
    - 'temperature_max'
    - 'temperature_mean'
    - 'spo2_min'
    - 'spo2_max'
    - 'spo2_mean'
    - 'glucose_min'
    - 'glucose_max'
    - 'glucose_mean'
  categorical_cols:
    - 'gender'
    - 'admission_type'
    - 'first_careunit'
  imputation_strategy: 'median'
  scale_numerics: True
  onehot_handle_unknown: 'ignore'

# Discharge Type Model (LGBM)
discharge_type_model:
  n_trials: 50

# Length of Stay Model (LGBM)
length_of_stay_model:
  n_trials: 50
