# Simplified configuration for the IUPESM 2025 challenge

random_seed: 42
data_dir: 'data/'
output_dir: 'outputs/'
los_column: 'lengthofStay'

data_paths:
  target_column: 'outcomeType'

# Preprocessing settings
preprocessing:
  numerical_cols:
    - 'patientAge'
    - 'sbp'
    - 'hematocrit'
    - 'hemoglobin'
    - 'leukocytes'
    - 'lymphocytes'
    - 'urea'
    - 'creatinine'
    - 'platelets'
    - 'diuresis'
  categorical_cols:
    - 'gender'
    - 'requestBedType'
    - 'admissionBedType'
    - 'admissionHealthUnit'
    - 'patientFfederalUnit'
    - 'icdCode'
  imputation_strategy: 'median'
  scale_numerics: True
  onehot_handle_unknown: 'ignore'

# Discharge Type Model (LGBM)
discharge_type_model:
  n_trials: 50

# Length of Stay Model (LGBM)
length_of_stay_model:
  n_trials: 50
